//! TEMPORARY verbatim copy of the asc-dex `ids` contract
//! (`crates/asc-dex/src/ids.rs`), so asc-bytecode can be built concurrently
//! before a dependency on asc-dex is wired. Owned by the Lead agent: at
//! wave-1 integration this module body is replaced by
//! `pub use asc_dex::ids::*;` — do not edit this file.

/// Sentinel used by the DEX format for "absent index" (e.g. no superclass).
pub const NO_INDEX: u32 = 0xFFFF_FFFF;

/// Index into `string_ids`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(transparent)]
pub struct StringIdx(pub u32);

/// Index into `type_ids`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(transparent)]
pub struct TypeIdx(pub u32);

/// Index into `proto_ids`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(transparent)]
pub struct ProtoIdx(pub u32);

/// Index into `field_ids`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(transparent)]
pub struct FieldIdx(pub u32);

/// Index into `method_ids`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(transparent)]
pub struct MethodIdx(pub u32);

/// Index into `call_site_ids` (DEX 038+).
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(transparent)]
pub struct CallSiteIdx(pub u32);

/// Index into `method_handles` (DEX 038+).
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[repr(transparent)]
pub struct MethodHandleIdx(pub u32);
