[package]
name = "asc-paranoid"
description = "Paranoid / LSParanoid string deobfuscation for ASC-RS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
asc-dex.workspace = true
asc-bytecode.workspace = true
