[package]
name = "asc-cli"
description = "CLI frontend for ASC-RS (getclass/findrefs parity)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "asc-rs"
path = "src/main.rs"

[dependencies]
asc-apk.workspace = true
asc-core.workspace = true
asc-manifest.workspace = true
asc-query.workspace = true
thiserror.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
asc-dex.workspace = true
zip = { version = "0.6", default-features = false }
crc32fast.workspace = true
