[package]
name = "asc-rebuild"
description = "Minimal standalone DEX reconstruction for ASC-RS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
asc-dex.workspace = true
asc-bytecode.workspace = true
sha1.workspace = true
adler2.workspace = true

[dev-dependencies]
asc-decompile.workspace = true
